# Generated by Django 4.2.8 on 2024-01-02 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuroCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2024, 1, 2, 8, 15, 0, 680402), null=True)),
                ('card_no', models.IntegerField()),
            ],
        ),
    ]
