# Generated by Django 4.2.8 on 2024-01-02 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turocards',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 8, 17, 32, 867322), null=True),
        ),
    ]
