# Generated by Django 4.2.8 on 2024-01-03 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_cards', '0003_alter_turocards_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turocards',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 20, 38, 36, 872918), null=True),
        ),
    ]
