# Generated by Django 4.2.8 on 2024-01-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_cards', '0004_alter_turocards_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='turocards',
            name='comments',
            field=models.TextField(default={}, verbose_name='{}'),
        ),
        migrations.AddField(
            model_name='turocards',
            name='likes',
            field=models.TextField(default=[], verbose_name='[]'),
        ),
        migrations.AddField(
            model_name='turocards',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turocards',
            name='status',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turocards',
            name='updatedAt',
            field=models.IntegerField(null=True),
        ),
    ]
