# Generated by Django 4.2.8 on 2024-01-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_cards', '0006_remove_turocards_username_turocards_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='turocards',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
