# Generated by Django 4.2.8 on 2024-01-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_cards', '0007_turocards_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turocards',
            name='comments',
            field=models.TextField(default=[], verbose_name='[]'),
        ),
    ]
