# Generated by Django 4.2.8 on 2024-01-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_cards', '0008_alter_turocards_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwappingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderUser', models.CharField(max_length=100)),
                ('receiverUser', models.CharField(max_length=100)),
                ('senderCard', models.IntegerField(default=0)),
                ('receiverCard', models.IntegerField(default=0)),
            ],
        ),
    ]
